export const associations = [
    { nom: "AAAVAM", description: "Association nationale de défense des intérêts des Victimes d’accidents des médicaments", image: "images/assos/aaavam.jpg" },
    { nom: "Actions Traitements", description: "Association de patients, agréée pour représenter les usagers du système de santé", image: "images/assos/actions-traitements.jpg" },
    { nom: "Addictions Alcool Vie Libre", description: "", image: "images/assos/addictions-alcool-vie-libre.jpg" },
    { nom: "ADEPA", description: "Association d’Études et de Défense des Personnes Amputées", image: "images/assos/adepa.jpg" },
    { nom: "ADMD", description: "Association pour le droit de mourir dans la dignité", image: "images/assos/admd.jpg" },
    { nom: "Advocacy France", description: "Association d’usagers en santé mentale, médico-sociale et sociale", image: "images/assos/advocacy-france.jpg" },
    { nom: "AFA Crohn RCH France", description: "Association François Aupetit, maladies inflammatoires chroniques intestinales, Maladie de Crohn et recto-colite hémorragique", image: "images/assos/afa-crohn-rch-france.jpg" },
    { nom: "AFDE", description: "Association française Des Dysplasies Ectodermiques", image: "images/assos/afde.jpg" },
    { nom: "AFDOC", description: "Association française des malades et opérés cardio-vasculaires", image: "images/assos/afdoc.jpg" },
    { nom: "AFGS", description: "Association Française du Gougerot Sjögren et des syndromes secs", image: "images/assos/afgs.jpg" },
    { nom: "AFH", description: "Association française des Hémophiles", image: "images/assos/afh.jpg" },
    { nom: "AFM-Téléthon", description: "Association française contre les myopathies", image: "images/assos/afm-telethon.jpg" },
    { nom: "AFPric", description: "Association française des polyarthritiques et des rhumatismes inflammatoires chroniques", image: "images/assos/afpric.jpg" },
    { nom: "AFRH", description: "Association française pour la Recherche sur l’Hidronadénite", image: "images/assos/afrh.jpg" },
    { nom: "AFS", description: "Association France Spondyloarthrites", image: "images/assos/afs.jpg" },
    { nom: "AFSA", description: "Association française du Syndrome d’Angelman", image: "images/assos/afsa.jpg" },
    { nom: "AFSEP", description: "Association française des Sclérosés en Plaques", image: "images/assos/afsep.jpg" },
    { nom: "AIDES", description: "Association de lutte contre le sida", image: "images/assos/aides.jpg" },
    { nom: "Alcool Écoute Joie & Santé", description: "", image: "images/assos/alcool-ecoute-joie-sante.jpg" },
    { nom: "Alliance Maladies Rares", description: "", image: "images/assos/alliance-maladies-rares.jpg" },
    { nom: "APF France handicap", description: "", image: "images/assos/apf-france-handicap.jpg" },
    { nom: "ASF", description: "Association des Sclérodermiques de France", image: "images/assos/asf.jpg" },
    { nom: "Autisme France", description: "", image: "images/assos/autisme-france.jpg" },
    { nom: "AVIAM", description: "Association d’aide aux victimes d’accidents médicaux", image: "images/assos/aviam.jpg" },
    { nom: "France Alzheimer", description: "", image: "images/assos/france-alzheimer.jpg" },
    { nom: "France Dépression", description: "", image: "images/assos/france-depression.jpg" }
];
