export const associations = [
    { nom: "AAAVAM", description: "Association nationale de défense des intérêts des Victimes d’accidents des médicaments" },
    { nom: "Actions Traitements", description: "Association de patients, agréée pour représenter les usagers du système de santé" },
    { nom: "Addictions Alcool Vie Libre", description: "" },
    { nom: "ADEPA", description: "Association d’Études et de Défense des Personnes Amputées" },
    { nom: "ADMD", description: "Association pour le droit de mourir dans la dignité" },
    { nom: "Advocacy France", description: "Association d’usagers en santé mentale, médico-sociale et sociale" },
    { nom: "AFA Crohn RCH France", description: "Association François Aupetit, maladies inflammatoires chroniques intestinales, Maladie de Crohn et recto-colite hémorragique" },
    { nom: "AFDE", description: "Association française Des Dysplasies Ectodermiques" },
    { nom: "AFDOC", description: "Association française des malades et opérés cardio-vasculaires" },
    { nom: "AFGS", description: "Association Française du Gougerot Sjögren et des syndromes secs" },
    { nom: "AFH", description: "Association française des Hémophiles" },
    { nom: "AFM-Téléthon", description: "Association française contre les myopathies" },
    { nom: "AFPric", description: "Association française des polyarthritiques et des rhumatismes inflammatoires chroniques" },
    { nom: "AFRH", description: "Association française pour la Recherche sur l’Hidronadénite" },
    { nom: "AFS", description: "Association France Spondyloarthrites" },
    { nom: "AFSA", description: "Association française du Syndrome d’Angelman" },
    { nom: "AFSEP", description: "Association française des Sclérosés en Plaques" },
    { nom: "AFVD", description: "Association francophone pour vaincre les douleurs" },
    { nom: "AFVS", description: "Association des familles victimes du saturnisme" },
    { nom: "AIDES", description: "Association de lutte contre le sida" },
    { nom: "AINP", description: "Association d’Information sur la Névralgie Pudendale" },
    { nom: "Alcool Écoute Joie & Santé", description: "" },
    { nom: "Alliance Maladies Rares", description: "" },
    { nom: "AMADYS", description: "Association des malades atteints de dystonie" },
    { nom: "AMALYSTE", description: "Association des victimes des syndromes de Lyell et de Stevens-Johnson" },
    { nom: "A.M.I nationale", description: "Association nationale de défense des malades, invalides et handicapés" },
    { nom: "ANDAR", description: "Association Nationale de Défense contre l'Arthrite Rhumatoïde" },
    { nom: "APAHJ", description: "Association Pour Adultes et Jeunes Handicapés" },
    { nom: "APF France handicap", description: "" },
    { nom: "APODEC", description: "Association Porteurs de défibrillateurs cardiaques" },
    { nom: "ARGOS 2001", description: "Aide aux personnes atteintes de troubles bipolaires et à leur entourage" },
    { nom: "ARSLA", description: "Association pour la recherche sur la sclérose latérale amyotrophique" },
    { nom: "ASBH", description: "Association nationale Spina Bifida et Handicaps Associés" },
    { nom: "ASF", description: "Association des Sclérodermiques de France" },
    { nom: "ASFC", description: "Association Française du Syndrome de Fatigue Chronique" },
    { nom: "Association des Brûlés de France", description: "" },
    { nom: "Autisme France", description: "" },
    { nom: "AVIAM", description: "Association d’aide aux victimes d’accidents médicaux" },
    { nom: "CADUS", description: "Conseil Aide et Défense des Usagers de la Santé" },
    { nom: "CLCV", description: "Consommation, logement, cadre de vie" },
    { nom: "CNAFAL", description: "Conseil National des Association Familiales Laïques" },
    { nom: "CNAFC", description: "Confédération Nationale des Associations Familiales Catholiques" },
    { nom: "CNAO", description: "Collectif National des Associations d'Obèses" },
    { nom: "E3M", description: "Association d’Entraide aux Malades de Myofasciite à Macrophages" },
    { nom: "EFAPPE Épilepsies", description: "Fédération des Associations en faveur des Personnes handicapées par des Épilepsies sévères" },
    { nom: "EndoFrance", description: "Association Française de lutte contre l’endométriose" },
    { nom: "ENDOmind", description: "Association d'actions contre l'endométriose" },
    { nom: "Entraid’Addict", description: "Fédération Alcool Assistance" },
    { nom: "Épilepsie-France", description: "" },
    { nom: "Familles de France", description: "Association de consommateurs et association d’usagers du système de santé" },
    { nom: "Familles Rurales", description: "Association de défense des consommateurs" },
    { nom: "Fédération française des Diabétiques", description: "" },
    { nom: "FFDSB", description: "Fédération Française pour le Don de Sang Bénévole" },
    { nom: "FFSA", description: "Fédération Française Sésame Autisme" },
    { nom: "Fédération nationale des Amis de la santé", description: "Association de prévention et de lutte contre les addictions et plus spécifiquement l’alcoolisme" },
    { nom: "FFCM", description: "Fédération française des Curistes médicalisés" },
    { nom: "FGCP", description: "Fédération Française des Associations de Greffés du Cœur et des Poumons" },
    { nom: "Fibromyalgie SOS", description: "" },
    { nom: "FNAPSY", description: "Fédération nationale des patients en psychiatrie" },
    { nom: "FNAR", description: "Fédération nationale des associations de retraités et préretraités" },
    { nom: "FNATH", description: "Association des accidentés de la vie" },
    { nom: "France Alzheimer", description: "" },
    { nom: "France Dépression", description: ""}
]
   
  