export const associations = [
    { nom: "A.M.I", description: "Association nationale de défense des malades, invalides et handicapés", image: "https://www.france-assos-sante.org/wp-content/uploads/2019/01/a.m.i-200x136.png" },
    { nom: "AAAVAM", description: "Association nationale de défense des intérêts des victimes d’accidents des médicaments", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/Aaavam-200x136.png" },
    { nom: "Addictions Alcool Vie Libre", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/addiction-alcool-vie-libre-200x136.png" },
    { nom: "ADEPA", description: "Association d’Etudes et de Défense des Personnes Amputées", image: "https://www.france-assos-sante.org/wp-content/uploads/2022/10/adepa-200x136.png" },
    { nom: "ADMD", description: "Association pour le droit de mourir dans la dignité", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/admd-200x136.png" },
    { nom: "Advocacy France", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2019/01/advocacy-france-200x136.png" },
    { nom: "AFA", description: "Association François Aupetit", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/afa-crohn-rch-200x136.png" },
    { nom: "AFDE", description: "Association française des Dysplasies Ectodermiques", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/afde-200x136.png" },
    { nom: "AFDOC", description: "Association française des malades et opérés cardio-vasculaires", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/afdoc-200x136.png" },
    { nom: "AFGS", description: "Association Française du Gougerot Sjögren et des syndromes secs", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/afgs-200x136.png" },
    { nom: "AFH", description: "Association française des Hémophiles", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/AFH-200x136.png" },
    { nom: "AFM", description: "Association française contre les myopathies", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/afm-telethon-200x136.png" },
    { nom: "AFPric", description: "Association française des Polyarthritiques et des rhumatismes inflammatoires chroniques", image: "https://www.france-assos-sante.org/wp-content/uploads/2019/01/afpric-200x136.png" },
    { nom: "AFS", description: "Association France Spondyloarthrites", image: "https://www.france-assos-sante.org/wp-content/uploads/2022/10/afs-spondy-200x136.png" },
    { nom: "AFSA", description: "Association francophone du syndrome d'Angelman", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/afsa-200x136.png" },
    { nom: "AFSEP", description: "Association française des sclérosés en plaques", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/afsep-200x136.png" },
    { nom: "AFVD", description: "Association francophone pour vaincre les douleurs", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/afvd-200x136.png" },
    { nom: "AFVS", description: "Association des Familles Victimes du Saturnisme", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/afvs-200x136.png" },
    { nom: "AIDES", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/aides-200x136.png" },
    { nom: "AINP", description: "Association d'Information sur la Névralgie Pudendale", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/ainp-200x136.png" },
    { nom: "Alcool Ecoute Joie & Santé", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/alcool-joie-et-sante-200x136.png" },
    { nom: "Alliance Maladies Rares", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/alliance-maladies-rares-200x136.png" },
    { nom: "Amadys", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2019/11/amadys-200x136.png" },
    { nom: "AMALYSTE", description: "Association des victimes des syndromes de Lyell et de Stevens-Johnson", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/amalyste-200x136.png" },
    { nom: "ANDAR", description: "Association nationale de défense contre l'arthrite rhumatoïde", image: "https://www.france-assos-sante.org/wp-content/uploads/2023/01/andar-200x136.png" },
    { nom: "APAJH", description: "Association Pour Adultes et Jeunes Handicapés", image: "https://www.france-assos-sante.org/wp-content/uploads/2022/04/apahj-200x136.png" },
    { nom: "APF France handicap", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/apf-france-handicap-200x136.png" },
    { nom: "APODEC", description: "Association des porteurs de dispositifs électriques cardiaques", image: "https://www.france-assos-sante.org/wp-content/uploads/2023/04/apodec-200x136.png" },
    { nom: "ARGOS 2001", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/argos-2001-200x136.png" },
    { nom: "ARSLA", description: "Association pour la recherche sur la SLA", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/arsla-200x136.png" },
    { nom: "ASBH", description: "Association nationale Spina Bifida et Handicaps Associés", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/asbh-200x136.png" },
    { nom: "ASF", description: "Association des Sclérodermiques de France", image: "https://www.france-assos-sante.org/wp-content/uploads/2019/11/asf-200x136.png" },
    { nom: "ASFC", description: "Association Française du Syndrome de Fatigue Chronique", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/asfc-200x136.png" },
    { nom: "Association des Brûlés de France", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2022/10/ABF-200x136.png" },
    { nom: "Association Française pour la Recherche sur l'Hidrosadénite", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2023/10/AFRH-200x136.png" },
    { nom: "Actions Traitements", description: "Association de patients, agréée pour représenter les usagers du système de santé", image: "https://www.france-assos-sante.org/wp-content/uploads/2019/11/actions-traitement-200x136.png" },
    { nom: "Autisme France", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/autisme-france-200x136.png" },
    { nom: "AVIAM", description: "Association d'aide aux victimes d'accidents médicaux et à leur famille", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/aviam-200x136.png" },
    { nom: "CADUS", description: "Conseil Aide & Défense des Usagers de la Santé", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/cadus-200x136.png" },
    { nom: "CLCV", description: "Association nationale de défense des consommateurs et usagers", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/clcv-200x136.png" },
    { nom: "CNAFAL", description: "Conseil national des Associations familiales laïques", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/afl-200x136.png" },
    { nom: "CNAFC", description: "Confédération des Associations familiales catholiques", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/CNAFC-200x136.png" },
    { nom: "CNAO", description: "Collectif national des Associations d'Obèses", image: "https://www.france-assos-sante.org/wp-content/uploads/2023/01/cnao-200x136.png" },
    { nom: "E3M", description: "Association Entraide aux Malades de Myofasciite à Macrophages", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/e3m-200x136.png" },
    { nom: "EFAPPE", description: "Fédération des Associations de personnes handicapées par des épilepsies sévères", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/efappe-200x136.png" },
    { nom: "EndoFrance", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2022/04/endofrance-200x136.png" },
    { nom: "ENDOmind", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2022/10/endomind-200x136.png" },
    { nom: "Entraid'addict", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/entraid-addict-200x136.png" },
    { nom: "Épilepsie France", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/epilepsie-france-200x136.png" },
    { nom: "Familles de France", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/familles-de-france-200x136.png" },
    { nom: "Familles Rurales", description: "Premier mouvement familial en France", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/familles-rurales-200x136.png" },
    { nom: "Fédération française des diabétiques", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/federation-francaise-des-diabetiques-200x136.png" },
    { nom: "Fédération Française pour le Don de Sang Bénévole", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2023/10/ffdsb-200x136.png" },
    { nom: "Fédération Française Sésame Autisme", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2019/11/sesame-autisme-200x136.png" },
    { nom: "FNAS", description: "Fédération nationale des Amis de la Santé", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/FNAS-200x136.png" },
    { nom: "FFCM", description: "Fédération française des Curistes médicalisés", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/ffcm-200x136.png" },
    { nom: "FGCP", description: "France Greffe Cœur et/ou Poumons", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/france-coeur-poumon-200x136.png" },
    { nom: "FibromyalgieSOS", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/fibromyalgie-sos-200x136.png" },
    { nom: "FNAPSY", description: "Fédération nationale des Associations d'usagers en psychiatrie", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/fnapsy-200x136.png" },
    { nom: "FNAR", description: "Fédération nationale des associations de retraités et préretraités", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/fnar-200x136.png" },
    { nom: "FNATH", description: "Association des accidentés de la vie", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/fnath-200x136.png" },
    { nom: "France Alzheimer", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/france-alzheimer-200x136.png" },
    { nom: "France Dépression", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2024/09/france-depression-2-200x136.png" },
    { nom: "France Lyme", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2022/04/france-lyme-200x136.png" },
    { nom: "France Parkinson", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/france-parkinson-200x136.png" },
    { nom: "France Rein", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/france-rein-200x136.png" },
    { nom: "HyperSupers – TDAH France", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2022/04/hypersupers-200x136.png" },
    { nom: "JALMALV", description: "Jusqu'à la mort accompagner la vie", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/jamalv-200x136.png" },
    { nom: "La Croix Bleue", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/croix-bleue-200x136.png" },
    { nom: "La CSF", description: "La Confédération syndicale des Familles", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/la-csf-200x136.png" },
    { nom: "La Ligue contre le cancer", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/ligue-contre-le-cancer-200x136.png" },
    { nom: "Le Lien", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2019/01/association-le-lien-200x136.png" },
    { nom: "Le Planning familial", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/planning-familial-200x136.png" },
    { nom: "Les petits frères des Pauvres", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/petits-freres-des-pauvres-200x136.png" },
    { nom: "Marfans", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/marfans-200x136.png" },
    { nom: "Priartem", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2019/11/priartem-200x136.png" },
    { nom: "Renaloo", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/renaloo-200x136.png" },
    { nom: "Réseau D.E.S. France", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/reseau-des-france-200x136.png" },
    { nom: "Réseau Environnement Santé (RES)", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/res-200x136.png" },
    { nom: "Schizo-oui", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/schizo-oui-200x136.png" },
    { nom: "SOS Hépatites Fédération", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/sos-hepatites-200x136.png" },
    { nom: "TRANSHÉPATE", description: "Fédération des Déficients et Transplantés Hépatiques", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/transhepate-1-200x136.png" },
    { nom: "UAFLMV", description: "Union des associations françaises de laryngectomisés et mutilés de la voix", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/ufmv-200x136.png" },
    { nom: "UFAL", description: "Union des Familles Laïques", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/ufal-200x136.png" },
    { nom: "UFC-Que Choisir", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/ufc-que-choisir-200x136.png" },
    { nom: "UNAF", description: "Union nationale des associations familiales", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/unaf-200x136.png" },
    { nom: "UNAFAM", description: "Union nationale de familles et amis de personnes malades et/ou handicapées psychiques", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/unafam-200x136.png" },
    { nom: "UNAFTC", description: "Union nationale des associations de familles de traumatisés crâniens et cérébro-lésés", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/unaftc-200x136.png" },
    { nom: "UNAPECLE", description: "Union nationale des Associations de parents d'enfants atteints de cancer ou leucémie", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/unapecle-200x136.png" },
    { nom: "Unapei", description: "Union nationale des associations de parents, de personnes handicapées mentales et de leurs amis", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/unapei-200x136.png" },
    { nom: "Vaincre la Mucoviscidose", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/vaincre-la-muco-200x136.png" },
    { nom: "Vivre comme avant", description: "", image: "https://www.france-assos-sante.org/wp-content/uploads/2022/10/vivre-comme-avant-200x136.png" },
    { nom: "VMEH", description: "Visite des Malades en Etablissements Hospitaliers", image: "https://www.france-assos-sante.org/wp-content/uploads/2018/11/vmeh-200x136.png" }
];